
#undef DEBUG
#undef DEBUG_CHATTER
#undef NDEBUG
#undef PHYSFS_SUPPORTS_ZIP
#undef PHYSFS_SUPPORTS_GRP
#undef PHYSFS_SUPPORTS_HOG
#undef PHYSFS_SUPPORTS_MVL
#undef PHYSFS_HAVE_READLINE
#undef PHYSFS_HAVE_LLSEEK

