#!/bin/sh

set -e
echo "Initial preparation...this can take awhile, so sit tight..."
perl -w -e 'exit 0 if (-f "Makefile.am"); my $x = `automake --version |head -n 1`; chomp($x); $x = 0.0 if ($x !~ s/\A.*?(\d+\.\d+).*\Z/$1/); if ($x < 1.5) { rename ("./Makefile.am.oldautomake", "./Makefile.am"); } else { rename ("./Makefile.am.newautomake", "./Makefile.am"); }'
aclocal
libtoolize --automake --copy --force
autoheader
automake --foreign --add-missing --copy
autoconf

echo "You are now ready to run ./configure ..."

