name: Build (OS/2)

on: [push, pull_request]

jobs:
  os2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: open-watcom/setup-watcom@v0
      - name: Build physfs.dll
        run: |
          cd src
          wmake -f Makefile.os2
          cd ..
      - name: distclean
        run: |
          cd src
          wmake -f Makefile.os2 distclean
          cd ..
